# Lesson 04: Numpy

- Used for working with tensors
- Provides vectors, matrices, and tensors
- Provides mathematical functions that operate on vectors, matrices, and tensors
- Implemented in Fortran and C in the backend

In [2]:
import numpy as np

## Making Arrays

In [3]:
arr = np.array([1, 2, 3])

In [4]:
print(arr, type(arr), arr.shape, arr.dtype)

[1 2 3] <class 'numpy.ndarray'> (3,) int64


In [5]:
matrix = np.array(
    [[1, 2, 3],
    [4, 5, 6.2]]
)

In [6]:
print(matrix, type(matrix), matrix.shape, matrix.dtype)

[[1.  2.  3. ]
 [4.  5.  6.2]] <class 'numpy.ndarray'> (2, 3) float64


In [7]:
a = np.zeros((10, 2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
a = np.ones((4, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
a = np.full((2, 3, 5), 6)
print(a)

[[[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]

 [[6 6 6 6 6]
  [6 6 6 6 6]
  [6 6 6 6 6]]]


In [10]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
a = np.random.random((5, 5))
print(a)

[[0.94118745 0.22994581 0.75183424 0.3433619  0.53614551]
 [0.4701853  0.68700713 0.3685086  0.19023418 0.17094098]
 [0.96813951 0.00628098 0.02295652 0.9007116  0.03263926]
 [0.56018717 0.13823581 0.71362452 0.57653406 0.9263221 ]
 [0.22776242 0.92652569 0.04206205 0.13036483 0.10911229]]


## Indexing

In [12]:
arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


The indexing format is: [rows , columns]

You can then slice the individual dimension as follows: [start : end , start : end]

In [13]:
print(arr[1:, 2:4])

[[ 8  9]
 [13 14]]


In [14]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a[ [0, 1, 2, 3], [1, 0, 2, 0] ])

print(a[0, 1], a[1, 0], a[2, 2], a[3, 0])
print(np.array([a[0, 1], a[1, 0], a[2, 2], a[3, 0]]))

[ 2  4  9 10]
2 4 9 10
[ 2  4  9 10]


In [15]:
b = np.array([1, 0, 2, 0])

print(a[np.arange(4), b])

[ 2  4  9 10]


In [16]:
a[np.arange(4), b] += 7

print(a)

[[ 1  9  3]
 [11  5  6]
 [ 7  8 16]
 [17 11 12]]


In [17]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

bool_a = (a > 5)

print(bool_a)

[[False False False]
 [False False  True]
 [ True  True  True]
 [ True  True  True]]


In [18]:
print(a[bool_a])

[ 6  7  8  9 10 11 12]


In [19]:
print(a[a>7])

[ 8  9 10 11 12]


## Data Types

In [22]:
b = np.array([1, 2, 3], dtype=np.float64)
print(b.dtype)

float64


https://numpy.org/doc/stable/reference/arrays.dtypes.html

## Operations

In [23]:
x = np.array([
    [1, 2],
    [3, 4]
])
y = np.array([
    [5, 6],
    [7, 8]
])

In [24]:
print(x, x.shape)
print(y, y.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)


In [28]:
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [29]:
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [30]:
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [31]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Matrix Multiplication

In [43]:
w = np.array([2, 4])
v = np.array([4, 6])

In [44]:
print(x)
print(y)
print(w)
print(v)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[2 4]
[4 6]


#### Vector-vector multiplication

In [48]:
print(v.dot(w))
print(np.dot(v, w))

32
32


#### Matrix-vector multiplication

In [46]:
print(x.dot(w))

[10 22]


#### Matrix multiplication

In [49]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Transpose

In [51]:
print(x)

print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

### Other Operations

In [55]:
print(x)

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


More array operations are listed here:

http://docs.scipy.org/doc/numpy/reference/routines.math.html

## Broadcasting

Broadcasting allows Numpy to work with arrays of different shapes. Operations which would have required loops can now be done without them hence speeding up your program.

In [57]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18],
])
print(x, x.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] (6, 3)


In [70]:
y = np.array([1, 2, 3])
print(y, y.shape)

[1 2 3] (3,)


### Loop Approach

In [61]:
z = np.empty_like(x)
print(z, z.shape)

[[ 93990358130640               0 140093575578096]
 [140093577442672 140093574520368 140093576112880]
 [140093577127280 140093577057072 140093575577648]
 [140093577543088 140093571607216 140093576757360]
 [140093575402288 140093576757424 140093577021872]
 [140093575091648 140093575610944 140093575612672]] (6, 3)


In [63]:
for i in range(x.shape[0]):
    z[i, :] = x[i, :] + y

print(z)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]
 [17 19 21]]


### Tile Approach

In [72]:
yy = np.tile(y, (6, 1))
print(yy, yy.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] (6, 3)


In [73]:
print(x + y)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]
 [17 19 21]]


### Broadcasting Approach

In [75]:
print(x, x.shape)
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] (6, 3)
[1 2 3] (3,)


In [76]:
print(x + y)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]
 [14 16 18]
 [17 19 21]]


- https://numpy.org/doc/stable/user/basics.broadcasting.html
- http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc
- http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

## Reshape

In [86]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

y = np.array([2, 2])

print(x, x.shape)
print(y, y.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[2 2] (2,)


### Transpose Approach

In [79]:
xT = x.T
print(xT)

[[1 4]
 [2 5]
 [3 6]]


In [81]:
xTw = xT + y
print(xTw)

[[3 6]
 [4 7]
 [5 8]]


In [82]:
x = xTw.T
print(x)

[[3 4 5]
 [6 7 8]]


In [85]:
print( (x.T + y).T)

[[3 4 5]
 [6 7 8]]


### Reshape Approach

In [88]:
print(y, y.shape)
y = np.reshape(y, (2, 1))
print(y, y.shape)

[2 2] (2,)
[[2]
 [2]] (2, 1)


In [89]:
print(x + y)

[[3 4 5]
 [6 7 8]]


# Resources

- http://docs.scipy.org/doc/numpy/reference/
- https://numpy.org/doc/stable/user/absolute_beginners.html
- https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md